CREATE SEQUENCE ADMIN_CHAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADMIN_MSG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEMBER_CHAT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE MEMBER_MSG_SEQ START WITH 1 INCREMENT BY 1;

--관리자와 사용자의 채팅방 생성--
INSERT INTO ADMIN_CHATTING(CHAT_ID, CHATTER1, CHATTER2, DELFLAG)
VALUES(ADMIN_CHAT_SEQ.NEXTVAL, 'ADMIN', 'AKAKTHSUS', 'N');

--관리자와 사용자의 메시지 전송--
INSERT INTO ADMIN_MESSAGE(CHAT_ID, MSG_CHAT_ID, MESSAGE_CONTENT, MESSAGE_DATE, SENDER)
VALUES((SELECT CHAT_ID FROM ADMIN_CHATTING WHERE CHATTER1 = 'ADMIN' AND CHATTER2 ='AKAKTHSUS')
,ADMIN_MSG_SEQ.NEXTVAL, '안녕하세요', SYSDATE, 'AKAKTHSUS');

--관리자 채팅방 조회
SELECT MESSAGE_CONTENT, MESSAGE_DATE
FROM ADMIN_MESSAGE
WHERE CHAT_ID = (SELECT CHAT_ID
								FROM ADMIN_CHATTING
								WHERE ('KYG8320') IN (CHATTER1, CHATTER2));
							
--관리자채팅방 삭제
UPDATE ADMIN_CHATTING
SET DELFLAG = 'Y' WHERE CHAT_ID = (SELECT CHAT_ID
								FROM ADMIN_CHATTING
								WHERE ('KYG8320') IN (CHATTER1, CHATTER2));

--사용자끼리의 채팅방 생성--
INSERT INTO MEMBER_CHATTING(CHAT_ID, CHATTER1, CHATTER2, DELFLAG)
VALUES(MEMBER_CHAT_SEQ.NEXTVAL, 'psc814', 'KYG8320', 'N');

--사용자끼리의 메시지 전송--
INSERT INTO MEMBER_MESSAGE(CHAT_ID, MSG_CHAT_ID, MESSAGE_CONTENT, MESSAGE_DATE, SENDER)
VALUES('1', MEMBER_MSG_SEQ.NEXTVAL, '네 안녕하세요', SYSDATE, (SELECT CHATTER1 FROM ADMIN_CHATTING));

--채팅방이 생성되어 있는지 체크
SELECT COUNT(*) FROM ADMIN_CHATTING WHERE CHATTER1 = 'ADMIN' AND CHATTER2 ='KYG8320';

SELECT * FROM ADMIN_MESSAGE;
SELECT * FROM ADMIN_CHATTING;
SELECT * FROM MEMBER_MESSAGE;
SELECT * FROM MEMBER_CHATTING;
SELECT * FROM MEMBERS;

