CREATE TABLE MESSAGE(
	MSG_CHAT_ID VARCHAR2(30) NOT NULL,
	MESSAGE_CONTENT VARCHAR2(1000) NOT NULL,
	MESSAGE_DATE DATE NOT NULL
);

ALTER TABLE MESSAGE ADD CONSTRAINTS MESSAGE_PK PRIMARY KEY(MSG_CHAT_ID);
ALTER TABLE MESSAGE ADD CONSTRAINTS MESSAGE_CHATTING_FK FOREIGN KEY(MSG_CHAT_ID) REFERENCES CHATTING(CHAT_ID);
--ALTER TABLE MESSAGE DROP CONSTRAINTS MESSAGE_CHATTING_FK;

CREATE TABLE CHATTING(
	CHAT_ID VARCHAR2(30) NOT NULL,
	CHATTER1 VARCHAR2(30) NOT NULL,
	CHATTER2 VARCHAR2(30) NOT NULL,
	DELFLAG CHAR(1) DEFAULT 'N'
);

ALTER TABLE CHATTING ADD CONSTRAINTS CHATTING_PK PRIMARY KEY(CHAT_ID);
ALTER TABLE CHATTING ADD CONSTRAINTS CHATTING_STADIUM_ADMIN_FK FOREIGN KEY(CHATTER1) REFERENCES STADIUM_ADMIN(ADMIN_ID);


CREATE TABLE STADIUM_ADMIN(
	ADMIN_ID VARCHAR2(30) NOT NULL,
	ADMIN_PW VARCHAR2(30) NOT NULL
);

ALTER TABLE STADIUM_ADMIN ADD CONSTRAINTS STADIUM_ADMIN_PK PRIMARY KEY(ADMIN_ID);

CREATE TABLE STADIUM(
	STADIUM_CODE VARCHAR2(30) NOT NULL,
	ADMIN_ID VARCHAR2(30) NOT NULL,
	STADIUM_NAME VARCHAR2(50) NOT NULL,
	AREA VARCHAR2(30) NOT NULL,
	SI_GUN_GU VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	INFO VARCHAR2(1000)
);

ALTER TABLE STADIUM ADD CONSTRAINTS STADIUM_PK PRIMARY KEY(STADIUM_CODE);

CREATE TABLE MEMBERS(
	MEMBER_ID VARCHAR2(30)
);

ALTER TABLE MEMBERS ADD CONSTRAINTS MEMBER_ID_PK PRIMARY KEY(MEMBER_ID)

CREATE TABLE BELONGED_TEAM(
	BELONGED_TEAM_CODE NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	TEAM_ID VARCHAR2(30) NOT NULL
);

ALTER TABLE BELONGED_TEAM ADD CONSTRAINTS BELONGED_TEAM_PK PRIMARY KEY(BELONGED_TEAM_CODE);
ALTER TABLE BELONGED_TEAM ADD CONSTRAINTS BELONGED_TEAM_MEMBERS_FK FOREIGN KEY(MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);
ALTER TABLE BELONGED_TEAM ADD CONSTRAINTS BELONGED_TEAM_TEAM_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID);

CREATE TABLE REPLY(
	REPLY_SEQ NUMBER NOT NULL,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REFER NUMBER NOT NULL,
	DEPTH NUMBER DEFAULT 0
);

ALTER TABLE REPLY ADD CONSTRAINTS REPLY_PK PRIMARY KEY(REPLY_SEQ); 

CREATE TABLE BOARD(
	BOARD_SEQ NUMBER NOT NULL,
	BOARD_ID VARCHAR2(30) NOT NULL,
	BOARD_TITLE VARCHAR2(30) NOT NULL,
	BOARD_CONTNET VARCHAR2(4000) NOT NULL,
	READCOUNT NUMBER DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE,
	CATEGORY_CODE VARCHAR2(10) NOT NULL,
	BOARD_COUNT NUMBER DEFAULT 0
);

ALTER TABLE BOARD ADD CONSTRAINTS BOARD_PK PRIMARY KEY(BOARD_SEQ);
ALTER TABLE BOARD ADD CONSTRAINTS BOARD_MEMBER_FK FOREIGN KEY(BOARD_ID) REFERENCES MEMBERS(MEMBER_ID);


CREATE TABLE CATEGORY(
	CATEGORY_CODE VARCHAR2(10) NOT NULL,
	CATEGORY_NAME VARCHAR2(20) NOT NULL
);

ALTER TABLE CATEGORY ADD CONSTRAINTS CATEGORY_PK PRIMARY KEY(CATEGORY_CODE);

CREATE TABLE TEAM(
	TEAM_ID VARCHAR2(30) NOT NULL,
	TEAM_PW VARCHAR2(30) NOT NULL,
	CAPTAIN_ID VARCHAR2(30) NOT NULL,
	CAPTAIN_PHONE_NUMBER VARCHAR2(20) NOT NULL,
	PLAYGROUND VARCHAR2(100) NOT NULL,
	STAT VARCHAR2(200) NOT NULL,
	QUESTION VARCHAR2(200) NOT NULL,
	ANSWER VARCHAR2(200) NOT NULL,
	DORMANT_ID VARCHAR2(30) DEFAULT 'N',
	MANNER NUMBER(1) NOT NULL
);

ALTER TABLE TEAM ADD CONSTRAINTS TEAM_ID_PK PRIMARY KEY(TEAM_ID);
--ALTER TABLE TEAM ADD CONSTRAINTS TEAM_BELONGED_TEAM_FK FOREIGN KEY(CAPTAIN_ID) REFERENCES BELONGED_TEAM(MEMBER_ID);
--ALTER TABLE TEAM DROP CONSTRAINTS TEAM_BELONGED_TEAM_FK;


CREATE TABLE SCHEDULE(
	SCHEDULE_ID NUMBER NOT NULL,
	STADIUM_CODE VARCHAR2(100) NOT NULL,
	GAME_DATE DATE NOT NULL,
	HOME_TEAM VARCHAR2(30),
	AWAY_TEAM VARCHAR2(30),
	SCHEDULE_CANCEL CHAR(1) DEFAULT 'N',
	RESERVATION CHAR(1) DEFAULT 'N',
	HOME_SCORE NUMBER,
	AWAY_SCORE  NUMBER
);

ALTER TABLE SCHEDULE ADD CONSTRAINT SCHEDULE_PK PRIMARY KEY(SCHEDULE_ID);
ALTER TABLE SCHEDULE ADD CONSTRAINTS SCHEDULE_STADIUM_FK FOREIGN KEY(STADIUM_CODE) REFERENCES STADIUM(STADIUM_CODE);
ALTER TABLE SCHEDULE ADD CONSTRAINTS SCHEDULE_TEAM_HOME_FK FOREIGN KEY(HOME_TEAM) REFERENCES TEAM(TEAM_ID);
ALTER TABLE SCHEDULE ADD CONSTRAINTS SCHEDULE_TEAM_AWAY_FK FOREIGN KEY(AWAY_TEAM) REFERENCES TEAM(TEAM_ID);


CREATE TABLE PICTURE(
	STADIUM_CODE VARCHAR2(100) NOT NULL,
	IMAGE1 VARCHAR2(30),
	IMAGE2 VARCHAR2(30),
	IMAGE3 VARCHAR2(30)
);

ALTER TABLE PICTURE ADD CONSTRAINT PICTURE_PK PRIMARY KEY(STADIUM_CODE);
ALTER TABLE PICTURE ADD CONSTRAINTS PICTURE_STADIUM_FK FOREIGN KEY(STADIUM_CODE) REFERENCES STADIUM(STADIUM_CODE);

CREATE TABLE MATCHING_CARD(
	MATCHING_NUMBER NUMBER NOT NULL,
	GAME_DATE DATE NOT NULL,
	REGIST_TEAM_ID VARCHAR2(30) NOT NULL,
	REGIST_TEAM_INFO VARCHAR2(300) NOT NULL,
	APPLIED_TEAM_ID VARCHAR2(30),
	APPLIED_TEAM_INFO VARCHAR2(300),
	RESERVATION_STADIUM VARCHAR2(50) DEFAULT '없음',
	MATCHING_STYLE VARCHAR2(10)
);

ALTER TABLE MATCHING_CARD ADD CONSTRAINT MATCHING_CARD_PK PRIMARY KEY(MATCHING_NUMBER);
ALTER TABLE MATCHING_CARD ADD CONSTRAINTS REGTEAM_MATCHING_CARD_FK FOREIGN KEY(REGIST_TEAM_ID) REFERENCES TEAM(TEAM_ID);
ALTER TABLE MATCHING_CARD ADD CONSTRAINTS APPTEAM_MATCHING_CARD_FK FOREIGN KEY(APPLIED_TEAM_ID) REFERENCES TEAM(TEAM_ID);


CREATE TABLE SCHEDULED_MATCHING(
	MATCHING_NUMBER NUMBER NOT NULL,
	COMMENTS VARCHAR2(100),
	HOME_SCORE NUMBER,
	AWAY_SCORE NUMBER
);

ALTER TABLE SCHEDULED_MATCHING ADD CONSTRAINTS SCHEDULED_MATCHING_PK PRIMARY KEY(MATCHING_NUMBER); 
ALTER TABLE SCHEDULED_MATCHING ADD CONSTRAINTS MATCHING_FK FOREIGN KEY(MATCHING_NUMBER) REFERENCES MATCHING_CARD(MATCHING_NUMBER);
CREATE TABLE STAT(
	TEAM_ID VARCHAR2(30) NOT NULL,
	ATTACK NUMBER,
	DEFENCE NUMBER,
	MANNER NUMBER
);

ALTER TABLE STAT ADD CONSTRAINTS STAT_TEAM_ID_PK PRIMARY KEY(TEAM_ID);
ALTER TABLE STAT ADD CONSTRAINTS STAT_TEAM_FK FOREIGN KEY(TEAM_ID) REFERENCES TEAM(TEAM_ID);

